project:
  type: website
  preview:
      port: 4200
      browser: false

website:
  title: "portfolio"
  navbar:
    left: 
      - text: Resume
        href: resume.qmd
      - text: University Performance
        href: university.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/mauricio-alejandro-prieto-palacios-a26682245/

format:
  html:
    theme: cosmo
    css: styles.css



